### ISSUE TITLE
Couple of settings menu values reset to plugin deactivatate and re-activate

### ISSUE THREAD

**Issue by Arsenal21** [Arsenal21/wp-express-checkout#10]
The values for the following settings field seem to reset after the plugin is deactivated and re-activated. It shouldn't happen.

Button Height
Button Width

Can you please take a look to see what you find?

**Comment by dikiyforester** [comment]
This happens in this code block: 
https://github.com/Arsenal21/wp-express-checkout/blob/f61da5954ed8f355f2ae90bc28794465dbbe259b/wp-express-checkout/public/class-wpec-main.php#L277-L298

So when the plugin activates and settings exist and option `btn_size` exists, this procedure restores the width and height to default values.

The option `btn_size` is not in use anywhere, so I suppose this happens only for you as you maybe have this option from the earlier versions. In my  install this works just fine since I've never had the option `btn_size`.

We can delete this code.

**Comment by Arsenal21** [comment]
okay. Lets delete that code. Please go ahead and delete it.

**Comment by Arsenal21** [comment]
Thank you
